namespace ProgrammingCode.Helpers
{
	public class LanguageApp
	{
		public static readonly List<string> LanguageEn = new List<string>
		{
		   new string("Home"),
		   new string("About"),
		   new string("Add Course"),
		   new string("Add Class"),
		   new string("Follow US"),
		   new string("Logout"),
		   new string("Welcome"),
		   new string("Complete"),
		   new string("Incomplete"),
		   new string("Start"),
		   new string("Continue"),
		   new string("ADD NEW COURSES"),
		   new string("Find Course"),
		   new string("SELECT AN COURSE"),
		   new string("Special Thanks"),
		   new string("Programmer"),
		   new string("Tester"),
		   new string("Privacy Policy"),
		   new string("DELETE ACCOUNT"),
		   new string($"Made with "),
		   new string("Register"),
		   new string("Login"),
		   new string("FirstName"),
		   new string("UserName"),
		   new string("Email"),
		   new string("Password"),
		   new string("Already have an account?"),
		   new string("If you don't have an account?"),
		   new string("By continuing, you automatically agree to our"),
		   new string("Terms of Service"),
		   new string("and"),
		   new string("Privacy Policy"),
		   new string("The user is already registered"),
		   new string("password or username are incorrect"),
		   new string("Alet!"),
		   new string("Information"),
		};

		public static readonly List<string> LanguageEs = new List<string>
		{
		   new string("Inicio"),
		   new string("Acerca De"),
		   new string("Añadir Curso"),
		   new string("Añadir Clase"),
		   new string("Siguienos"),
		   new string("Cerrar Seccion"),
		   new string("Bienvenido"),
		   new string("Completo"),
		   new string("Incompleto"),
		   new string("Iniciar"),
		   new string("Continuar"),
		   new string("AÑADIR NUEVO CURSO"),
		   new string("Buscar Un Curso"),
		   new string("SELECIONAR UN CURSO"),
		   new string("Agradecimientos"),
		   new string("Programador"),
		   new string("Pruebas"),
		   new string("Politicas de Privacidad"),
		   new string("BORRAR CUENTA"),
		   new string("Hecho con "),
		   new string("Registrarse"),
		   new string("Iniciar Seccion"),
		   new string("Nombre"),
		   new string("Usuario"),
		   new string("Email"),
		   new string("Contraseña"),
		   new string("Ya tienes una Cuenta?"),
		   new string("Sino tienes una Cuenta?"),
		   new string("Al continuar acceptas automaticamente nuestras"),
		   new string("Termino de Servicio"),
		   new string("y"),
		   new string("Politicas de Privacidad"),
		   new string("El usuario ya esta Refistrar"),
		   new string("Contraseña o usuario incorrectos"),
		   new string("Alerta!"),
		   new string("Información"),
		};
	}
}