namespace ProgrammingCode.Helpers.MyData
{
    public class MyDataImagesClass
    {
        public static List<MyInfo> MyImages = new List<MyInfo>
        {
            new MyInfo { Id = 1, Name = "" },
            new MyInfo { Id = 2, Name = "" },
            new MyInfo { Id = 3, Name = "" },
            new MyInfo { Id = 4, Name = "" },
            new MyInfo { Id = 5, Name = "" },
            new MyInfo { Id = 6, Name = "" },
            new MyInfo { Id = 7, Name = "" },
            new MyInfo { Id = 8, Name = "" },
            new MyInfo { Id = 9, Name = "" },
            new MyInfo { Id = 10, Name = "" },
            new MyInfo { Id = 11, Name = "" },
            new MyInfo { Id = 12, Name = "" },
            new MyInfo { Id = 13, Name = "" },
            new MyInfo { Id = 14, Name = "" },
            new MyInfo { Id = 15, Name = "" },
            new MyInfo { Id = 16, Name = "" },
            new MyInfo { Id = 17, Name = "" },
            new MyInfo { Id = 18, Name = "" },
            new MyInfo { Id = 19, Name = "" },
            new MyInfo { Id = 20, Name = "" },
            new MyInfo { Id = 21, Name = "" },
            new MyInfo { Id = 22, Name = "" },
            new MyInfo { Id = 23, Name = "" },
            new MyInfo { Id = 24, Name = "" },
            new MyInfo { Id = 25, Name = "" },
            new MyInfo { Id = 26, Name = "" },
            new MyInfo { Id = 27, Name = "" },
            new MyInfo { Id = 28, Name = "" },
            new MyInfo { Id = 29, Name = "" },
            new MyInfo { Id = 30, Name = "" },
            new MyInfo { Id = 31, Name = "" },
            new MyInfo { Id = 32, Name = "" },
            new MyInfo { Id = 33, Name = "" },
            new MyInfo { Id = 34, Name = "" },
            new MyInfo { Id = 35, Name = "" },
            new MyInfo { Id = 36, Name = "" },
            new MyInfo { Id = 37, Name = "" },
            new MyInfo { Id = 38, Name = "" },
            new MyInfo { Id = 39, Name = "" },
            new MyInfo { Id = 40, Name = "" },
            new MyInfo { Id = 41, Name = "" },
            new MyInfo { Id = 42, Name = "" },
            new MyInfo { Id = 43, Name = "" },
            new MyInfo { Id = 44, Name = "" },
            new MyInfo { Id = 45, Name = "" },
            new MyInfo { Id = 46, Name = "" },
            new MyInfo { Id = 47, Name = "" },
            new MyInfo { Id = 48, Name = "" },
            new MyInfo { Id = 49, Name = "" },
            new MyInfo { Id = 50, Name = "" },
            new MyInfo { Id = 51, Name = "" },
            new MyInfo { Id = 52, Name = "" },
            new MyInfo { Id = 53, Name = "" },
            new MyInfo { Id = 54, Name = "" },
            new MyInfo { Id = 55, Name = "" },
            new MyInfo { Id = 56, Name = "" },
            new MyInfo { Id = 57, Name = "" },
            new MyInfo { Id = 58, Name = "" },
            new MyInfo { Id = 59, Name = "" },
            new MyInfo { Id = 60, Name = "" },
            new MyInfo { Id = 61, Name = "" },
            new MyInfo { Id = 62, Name = "" },
            new MyInfo { Id = 63, Name = "" },
            new MyInfo { Id = 64, Name = "" },
            new MyInfo { Id = 65, Name = "" },
            new MyInfo { Id = 66, Name = "" },
            new MyInfo { Id = 67, Name = "" },
            new MyInfo { Id = 68, Name = "" },
            new MyInfo { Id = 69, Name = "" },
            new MyInfo { Id = 70, Name = "" },
            new MyInfo { Id = 71, Name = "" },
            new MyInfo { Id = 72, Name = "" },
            new MyInfo { Id = 73, Name = "" },
            new MyInfo { Id = 74, Name = "" },
            new MyInfo { Id = 75, Name = "" },
            new MyInfo { Id = 76, Name = "" },
            new MyInfo { Id = 77, Name = "" },
            new MyInfo { Id = 78, Name = "" },
            new MyInfo { Id = 79, Name = "" },
            new MyInfo { Id = 80, Name = "" },
            new MyInfo { Id = 81, Name = "" },
            new MyInfo { Id = 82, Name = "" },
            new MyInfo { Id = 83, Name = "" },
            new MyInfo { Id = 84, Name = "" },
            new MyInfo { Id = 85, Name = "" },
            new MyInfo { Id = 86, Name = "" },
            new MyInfo { Id = 87, Name = "" },
            new MyInfo { Id = 88, Name = "" },
            new MyInfo { Id = 89, Name = "" },
            new MyInfo { Id = 90, Name = "" },
             
            new MyInfo { Id = 91, Name = "" },
            new MyInfo { Id = 92, Name = "" },
            new MyInfo { Id = 93, Name = "" },
            new MyInfo { Id = 94, Name = "" },
            new MyInfo { Id = 95, Name = "" },
            new MyInfo { Id = 96, Name = "" },
            new MyInfo { Id = 97, Name = "" },
            new MyInfo { Id = 98, Name = "" },
            new MyInfo { Id = 99, Name = "" },
            new MyInfo { Id = 100, Name = "" },
            new MyInfo { Id = 101, Name = "" },
            new MyInfo { Id = 102, Name = "" },
            new MyInfo { Id = 103, Name = "" },
            new MyInfo { Id = 104, Name = "" },
            new MyInfo { Id = 105, Name = "" },
            new MyInfo { Id = 106, Name = "" },
            new MyInfo { Id = 107, Name = "" },
            new MyInfo { Id = 108, Name = "" },
            new MyInfo { Id = 109, Name = "" },
            new MyInfo { Id = 110, Name = "" },
            new MyInfo { Id = 111, Name = "" },
            new MyInfo { Id = 112, Name = "" },
            new MyInfo { Id = 113, Name = "" },
            new MyInfo { Id = 114, Name = "" },
            new MyInfo { Id = 115, Name = "" },
            new MyInfo { Id = 116, Name = "" },
            new MyInfo { Id = 117, Name = "" },
            new MyInfo { Id = 118, Name = "" },
            new MyInfo { Id = 119, Name = "" },
            new MyInfo { Id = 120, Name = "" },
            new MyInfo { Id = 121, Name = "" },
            new MyInfo { Id = 122, Name = "" },
            new MyInfo { Id = 123, Name = "" },
            new MyInfo { Id = 124, Name = "" },
            new MyInfo { Id = 125, Name = "" },
            new MyInfo { Id = 126, Name = "" },
            new MyInfo { Id = 127, Name = "" },
            new MyInfo { Id = 128, Name = "" },
            new MyInfo { Id = 129, Name = "" },
            new MyInfo { Id = 130, Name = "" },
            new MyInfo { Id = 131, Name = "" },
            new MyInfo { Id = 132, Name = "" },
            new MyInfo { Id = 133, Name = "" },
            new MyInfo { Id = 134, Name = "" },
            new MyInfo { Id = 135, Name = "" },
            new MyInfo { Id = 136, Name = "" },
            new MyInfo { Id = 137, Name = "" },
            new MyInfo { Id = 138, Name = "" },
            new MyInfo { Id = 139, Name = "" },
            new MyInfo { Id = 140, Name = "" },
        };
        
    }
    public class MyInfo
    {
        public int Id { get; set; }
        public string Name { get; set; } = string.Empty;
    }
    
}

